services:
  vllm-server:
    image: vllm/vllm-openai:latest
    ports:
      - "8001:8000"
    volumes:
      - ${HF_HOME}:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    ipc: host
    command: >
      --model huihui-ai/Huihui-Qwen3-VL-30B-A3B-Instruct-abliterated
      --disable-log-requests
      --tensor-parallel-size 8
      --enable-expert-parallel
      --mm-encoder-tp-mode data
      --max-model-len 32768
      --enable-auto-tool-choice
      --tool-call-parser hermes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
